### ISSUE TITLE
Maybe support single markdown file

### ISSUE THREAD

**Issue by vivaxy** [int64ago/node-reveal#1]
I am using `reveal.js` these days, I found it's hard to setup all configurations for `reveal.js`. So I decide to write a client tool. This tool is installed in the project, and within the `package.json`, if I just need to setup like:
```js
{
  //..
  "scripts": {
    "ppt": "reveal --markdown ./ppt/presentation.md"
  }
}
```

And I find your project, which is pretty cool.

But I'd like to have the tool not generation any files within my project. If it could just read my markdown file, it would be every nice. So we are doing it in different approaches, maybe I'll start own project.

**Comment by int64ago** [comment]
Yes, I understand what you mean. `reveal.js` supports markdown natively, so it's possible to render slides from markdown files directly, but the markdown file should be well formatted.

IMO, it's not a good idea, for these may sacrifice the flexibility of `reveal.js`.

**Comment by vivaxy** [comment]
简单地写了一个：https://github.com/vivaxy/node-reveal
