### ISSUE TITLE
如何与reveal 官方版本保持一致的？

### ISSUE THREAD

**Issue by leson** [int64ago/node-reveal#5]
Hi Cody,

May i know how did you to align with official version of reveal ?

Thanks in advance,
Leson

**Comment by int64ago** [comment]
这个是通过 git submodule 加入的，目前是 43eada79901830702bd40dce857831aef8e76759

可以认为是最新的（最新的多了条跟功能无关的 commit）

**Comment by leson** [comment]
> 这个是通过 git submodule 加入的，目前是 43eada79901830702bd40dce857831aef8e76759
> 
> 可以认为是最新的（最新的多了条跟功能无关的 commit）

Thanks a million!
